name: Node.js Express Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2.5.3
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Run tests
      run: npm test
